### ISSUE TITLE
Even data distribution

### ISSUE THREAD

**Issue by ibro45** [HPI-DeepLearning/crnn-lid#10]
Hi,

Just a quick question - are the youtube audio samples evenly distributed between languages in some step? If they are, would you please tell me in which script is it happening? ~~If they aren't, could you explain why?~~ Sorry, I've just read in the paper that they are.

I'd also like to thank you for writing the paper in a really comprehensive way!

**Comment by Bartzi** [comment]
Yes, the audio files are evenly distributed. [This function](https://github.com/HPI-DeepLearning/crnn-lid/blob/master/data/create_csv.py#L33) that is for instance used by [this](https://github.com/HPI-DeepLearning/crnn-lid/blob/master/data/wav_to_spectrogram.py) script, distributes the audio files.

**Comment by ibro45** [comment]
Perfect, thank you very much!
