### ISSUE TITLE
File name issue

### ISSUE THREAD

**Issue by Varuzhan97** [HPI-DeepLearning/crnn-lid#16]
Hi. I am getting this error when I am trying to run prediction for a single mp3 file:
Using TensorFlow backend.
('SpectrogramGenerator Exception: ', IOError(2, 'No such file or directory'), 'aaaa.mp3')

File is located in crnn-lid-master folder. Terminal command is:
python keras/predict.py --model home/varuzhan/Desktop/crnn-lid-master/web-server/model/2017-01-31-14-29-14.CRNN_EN_DE_FR_ES_CN_RU.model --input aaaa.mp3

Thanks.

**Comment by Bartzi** [comment]
you should try to put your file into the `keras` folder, or provide an absolute path to the file :wink:

**Comment by Varuzhan97** [comment]
I put file into keras. Again the same error. Before posting this error I have tried with absalute path and sll was the same.

**Comment by Varuzhan97** [comment]
Or it gives "input is not a file"

**Comment by Varuzhan97** [comment]
File is an mp3 file(downloaded from youtube).
