### ISSUE TITLE
Predict single audio(mp3 file).

### ISSUE THREAD

**Issue by Varuzhan97** [HPI-DeepLearning/crnn-lid#17]
command:
python3 predict.py --model 2017-01-31-14-29-14.CRNN_EN_DE_FR_ES_CN_RU.model --input aaa.wav

error:
Traceback (most recent call last):
  File "predict.py", line 7, in <module>
    from data_loaders.SpectrogramGenerator import SpectrogramGenerator
  File "/home/varuzhan/Desktop/crnn-lid-master/keras/data_loaders/__init__.py", line 2, in <module>
    from .image_loader import ImageLoader
  File "/home/varuzhan/Desktop/crnn-lid-master/keras/data_loaders/image_loader.py", line 2, in <module>
    from scipy.misc import imread
ImportError: cannot import name 'imread'

**Comment by Bartzi** [comment]
did you install all requirements with `pip install -r requirements.txt` or did you install things by yourself?

**Comment by Varuzhan97** [comment]
I have installed somethings by me somethings by requirements.

**Comment by Bartzi** [comment]
you get this error, because your version of scipy is too new. So, either you install the correct version, or you fix the problem yourself.

**Comment by Varuzhan97** [comment]
which one is the correct version?

**Comment by Bartzi** [comment]
the one in the file `requirements.txt` :wink:

**Comment by Varuzhan97** [comment]
ok. thanks

**Comment by Varuzhan97** [comment]
I have done how you said. I have installed all requirements. Now error is:

('SpectrogramGenerator Exception: ', IOError(2, 'No such file or directory'), '/home/varuzhan/Desktop/crnn-lid-master/keras/aaa.mp3')
Traceback (most recent call last):
  File "/home/varuzhan/Desktop/crnn-lid-master/keras/predict.py", line 41, in <module>
    predict(cli_args)
  File "/home/varuzhan/Desktop/crnn-lid-master/keras/predict.py", line 16, in predict
    data = np.stack(data)
  File "/home/varuzhan/.local/lib/python2.7/site-packages/numpy/core/shape_base.py", line 335, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

**Comment by Bartzi** [comment]
are you sure the file `/home/varuzhan/Desktop/crnn-lid-master/keras/aaa.mp3` exists? The program can not find this file.

**Comment by Varuzhan97** [comment]
Problem was with requirements. I have solved it.

**Comment by Aksh97** [comment]
@Varuzhan97 How did you solve the problem of requirements.txt?
Can you please add to your repo?
