### ISSUE TITLE
ValueError: arrays must all be same length

### ISSUE THREAD

**Issue by Bini55** [HPI-DeepLearning/crnn-lid#19]
While running the tsne.py code I'm getting the following error. 

Traceback (most recent call last):
  File "tsne.py", line 100, in <module>
    visualize_cluster(cli_args)
  File "tsne.py", line 84, in visualize_cluster
    plot_with_labels(lowD_weights, labels, config["label_names"], cli_args.plot_name)
  File "tsne.py", line 17, in plot_with_labels
    df = DataFrame({"x": lowD_Weights[:, 0], "y": lowD_Weights[:, 1], "label": labels})
  File "/home/bini/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 275, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/home/bini/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 411, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/home/bini/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 5496, in _arrays_to_mgr
    index = extract_index(arrays)
  File "/home/bini/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 5544, in extract_index
    raise ValueError('arrays must all be same length')
ValueError: arrays must all be same length

**Comment by Bartzi** [comment]
What exactly did you try to do? Did you install all requirements as pointed out in `requirements.txt`?

**Comment by Bini55** [comment]
I'm doing classification task .I'm able to run the train.py and predicted.py but unable to run the evaluate and tsne file
yes..installed all requirements as pointed out in requirements.txt

**Comment by Bini55** [comment]
Can we predict all files instead of one files using predict.py and visualize it (confusion matrix and bar graph), for that how we can  edit or change the predict.py code.Can you please help me for that ?

**Comment by Bartzi** [comment]
yes, you can surely do that. Just add a loop where you load each file, put it through the classifier and save the prediction result. You can then generate your visualizations, e.g. a confusion matrix. Should not be too difficult to that :wink: .

**Comment by Bini55** [comment]
Can you please tell me why we use songs.py file and also
    eval("/data/tom/songs/hiphop")
    eval("/data/tom/songs/pop")  indicates which directory?

**Comment by Bini55** [comment]
Ok.....Can you please tell me why we use songs.py file and also
eval("/data/tom/songs/hiphop")
eval("/data/tom/songs/pop") indicates which directories?

**Comment by Bini55** [comment]
Ok....I'm not sure but I will try to do that.Can you please tell me why we use songs.py file.Is it required (mandatory .py file) and also
eval("/data/tom/songs/hiphop")
eval("/data/tom/songs/pop") indicates which directories?

**Comment by Bini55** [comment]
If you don't mind can you please tell me in the following python files which directories are mentioned, actually I have my own dataset (having different folders) so I'm confused about the path (which path should). 
**DirectoryLoader.py**
line:75
a = DirectoryLoader("/Users/therold/Downloads/Speech Data/EU Speech", {"pixel_per_second": 50, "input_shape": [129, 100, 1], "batch_size": 32, "num_classes": 4}, shuffle=True)
line:85
scipy.misc.imsave("/Users/therold/Downloads/Speech Data/EU Speech/png/%s.png" % i, np.squeeze(image) * 255.)

**MusicBackgroundSpectrogramGenerator.py**

line:131
a = MusicBackgroundSpectrogramGenerator("/Users/therold/Uni/master-thesis/datasets/EUSpeech/english/input.wav", {"pixel_per_second": 50, "input_shape": [129, 100, 1], "batch_size": 32, "num_classes": 4}, shuffle=True)

**NoisyBackgroundSpectrogramGenerator.py**

line:139
a = SpectrogramGenerator("/Users/therold/Uni/master-thesis/datasets/EU Speech/english/input.wav", {"pixel_per_second": 50, "input_shape": [129, 100, 1], "batch_size": 32, "num_classes": 4}, shuffle=True)

**SpectrogramGenerator.py**

line:127
a = SpectrogramGenerator("/extra/tom/news2/raw", {"pixel_per_second": 50, "input_shape": [129, 100, 1], "batch_size": 32, "num_classes": 4}, shuffle=True)

**Comment by Bini55** [comment]
If you don't mind can you please tell me in the following python files which directories are mentioned, actually I have my own dataset (having different folders) so I'm confused about the path (which path should).

**DirectoryLoader.py**

line:75

a = DirectoryLoader("/Users/therold/Downloads/Speech Data/EU Speech", {"pixel_per_second": 50, "input_shape": [129, 100, 1], "batch_size": 32, "num_classes": 4}, shuffle=True)

line:85

scipy.misc.imsave("/Users/therold/Downloads/Speech Data/EU Speech/png/%s.png" % i, np.squeeze(image) * 255.)

**MusicBackgroundSpectrogramGenerator.py**

line:131

a = MusicBackgroundSpectrogramGenerator("/Users/therold/Uni/master-thesis/datasets/EUSpeech/english/input.wav", {"pixel_per_second": 50, "input_shape": [129, 100, 1], "batch_size": 32, "num_classes": 4}, shuffle=True)

**NoisyBackgroundSpectrogramGenerator.py**

line:139

a = SpectrogramGenerator("/Users/therold/Uni/master-thesis/datasets/EU Speech/english/input.wav", {"pixel_per_second": 50, "input_shape": [129, 100, 1], "batch_size": 32, "num_classes": 4}, shuffle=True)

**SpectrogramGenerator.p**y

line:127

a = SpectrogramGenerator("/extra/tom/news2/raw", {"pixel_per_second": 50, "input_shape": [129, 100, 1], "batch_size": 32, "num_classes": 4}, shuffle=True)

**Comment by Bartzi** [comment]
oh :sweat_smile: there are still hard coded paths in the code. That is unfortunate...

exchange those paths with paths on your system. in **DirectoryLoader.py**, line 75 for instance let it point to a folder containing your dataset (i think) and so on. in the end it also highly depends on the structure of your dataset if it is different than expected, it might not work. Your best bet is to try and in case it does not work to adapt some code...

**Comment by Bini55** [comment]
Ok.....Let me try.....I have a question regarding the prediction (predict.py)...Is it predict only 10s duration audio files or can be predicted with long (1min,10min,etc) or short (2s,5s,6s)duration audio files?

**Comment by Bini55** [comment]
When I  run predict.py file it shows error **raise ValueError ('need at least one array to stack')
ValueError: need at least one array to stack**. Any idea why that error is coming?
