### ISSUE TITLE
Models origin

### ISSUE THREAD

**Issue by lvaleriu** [HPI-DeepLearning/crnn-lid#2]
Hello. I'm seeing some models who are described as  "TOPCODER etc". Ex: topcoder_5s_finetune, Topcoder_CRNN, etc.

Are these models from the SpokenLanguage topcoder contest? If this is the case, can you share the weights?

Thanks in advance!

Your project is SUPERB by the way!

**Comment by Bartzi** [comment]
Hi,

the name of these models describes the method and architecture of the model. We did not use any data from the contest you are mentioning and hence have unfortunately no weights we could share with you.

Thanks for your PR ;)

**Comment by tlonic** [comment]
Is there a reference that describes these architectures? I don't see them mentioned in the paper.

**Comment by Bartzi** [comment]
Those models have been used during testing and initial research, but we did not include them in the paper, as they did not perform that well. They are included in the repository for reference. Just in case somebody wants to play around with them.

**Comment by tlonic** [comment]
But is there any reference to where they came from? It seems like from some
topcoder contest?
