### ISSUE TITLE
Train issue.

### ISSUE THREAD

**Issue by Varuzhan97** [HPI-DeepLearning/crnn-lid#20]
I am getting this error when trying to process train:

Logging to logs/2020-04-09-16-19-09
Traceback (most recent call last):
  File "/home/varuzhan/Desktop/crnn-lid-master/keras/train.py", line 85, in <module>
    shutil.copytree("models", log_dir)  # creates the log_dir
  File "/usr/lib/python2.7/shutil.py", line 194, in copytree
    names = os.listdir(src)
OSError: [Errno 2] No such file or directory: 'models'

**Comment by Bartzi** [comment]
you seem to be starting the training from the wrong directory.

**Comment by Varuzhan97** [comment]
And what I must correct?
please explain me process of training step by step if it possible.
