### ISSUE TITLE
Training steps.

### ISSUE THREAD

**Issue by Varuzhan97** [HPI-DeepLearning/crnn-lid#21]
Can anyone explaint me training process step by step.I have tried every method and way but no results only errors:).

**Comment by Bartzi** [comment]
Well, you first download the data with all tools in the `data` directory, then you create a `config.yaml` based on our template, and then you start the training. It is as easy as that.

**Comment by Varuzhan97** [comment]
Yes I have done. Program shows that download is in process but there in no any downloaded data in folder.

**Comment by Bartzi** [comment]
This is odd :shrug: are you using YouTube download?
In the end the question is: what are you exactly trying?

**Comment by Varuzhan97** [comment]
I am trying to download data from youtube using download_youtube.py.So what must create download_youtube after downloading data?

**Comment by Bartzi** [comment]
your output directory should contain some subdirectories, such as `raw` and in there you should find `.wav` files. 
and you should also have a `.csv` file

**Comment by Varuzhan97** [comment]
After downloading data it creates train test validation csv files but this files are empty.

**Comment by Bartzi** [comment]
your output directory should contain some subdirectories, such as `raw` and in there you should find `.wav` files. 
and you should also have a `.csv` file

**Comment by Bartzi** [comment]
hmm, did the script provide some output which videos it tried to download? Seems that the videos are not found.

**Comment by Varuzhan97** [comment]
Yes.Look my subdirectory contains raw folder with .wav file . after downloading data and finishing download .csv files are still empty

**Comment by Varuzhan97** [comment]
must i create spectograms after downloading data?
