### ISSUE TITLE
Failing to import model package

### ISSUE THREAD

**Issue by Arafat4341** [HPI-DeepLearning/crnn-lid#25]
Inside `keras/models` package there is an `__init__.py` file in which author has imported all the self created modules.
I am getting error: `ModuleNotFoundError: No module named 'topcoder'`. Self-created modules are failing to import.

Why am I getting this? What should I do? 
Thanks in advance!

**Comment by Arafat4341** [comment]
It was a version issue. I got it!

**Comment by shaunakjoshi1312** [comment]
@Arafat4341 which version issue? I directly installed packages from requirements.txt and still getting error
