### ISSUE TITLE
value of nb_val_samples is none: validation_data_generator.get_num_files() returns 0

### ISSUE THREAD

**Issue by Arafat4341** [HPI-DeepLearning/crnn-lid#27]
I am trying to run the `train.py` script.  I can see in the training section in line 59:
`nb_val_samples=validation_data_generator.get_num_files()`

`validation_data_generator.get_num_files()` is returning 0. 
Thats why I am getting the exception:
`Exception: When using a generator for validation data, you must specify a value for "nb_val_samples".`

Kindly tell me whats going wrong!
Thanks in advance!

**Comment by Bartzi** [comment]
It seems you did not supply a valid `validation.csv` in your `config.yaml`. This is why the `validation_data_generator` says that there are `0` files to load
