### ISSUE TITLE
some errors when run python train.py

### ISSUE THREAD

**Issue by Mitchell1314** [HPI-DeepLearning/crnn-lid#3]
Hi sir,
   I am trying to using your crnn-lid. Firstly I have download the audio by using ./download-data.sh and convert audio files to spectrograms by running "python wav_to_spectrogram.py" .Then I set all the desired properties and hyperparameters in the config.yaml file. After that, I go into the `keras` directory and run "python train.py". Unfortunately, I got something wrong as follows:
    
![2018-01-05 16-56-13](https://user-images.githubusercontent.com/15179223/34602087-73f04d2a-f239-11e7-8c65-a34ab06b7f32.png)
  Can you give me some help? Waiting for your reply. Thank you!

**Comment by Bartzi** [comment]
It seems that you did not specify a correct value for `validation_data_dir` in `config.yaml` or something with the generated `validation.csv` is wrong. Have you checked that?

**Comment by Mitchell1314** [comment]
Here is my configure.yaml:
![2018-01-05 17-07-50](https://user-images.githubusercontent.com/15179223/34602603-5555668c-f23b-11e7-9e66-7fcf14dab005.png)

**Comment by Bartzi** [comment]
`validation_data_dir` should be the path to a directory not to a file. So in your case it should be `/home/winlab-crnn/crnn-lid/data/picture`, this hold true for every path! SO you'll also have to change `train_data_dir` and `test_data_dir`.

The suffix `dir` is there to tell you that this configuration option should point to a directory.

Hope I could help!
And sorry that it took me so long to answer. I did not see your response earlier...

**Comment by Bartzi** [comment]
closing this because it got stale

**Comment by shiva33232** [comment]
same error occured as mentioned above unable to solve issue with your solution mentioned above

**Comment by Varuzhan97** [comment]
@shiva33232 Hi. Have you solved this error?
